package model.ViewObject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 28 15:21:00 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CandidatesAssignedInterviewerRowImpl extends ViewRowImpl {


    /**
     * This is the default constructor (do not remove).
     */
    public CandidatesAssignedInterviewerRowImpl() {
    }
}

