package model.ViewObject;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 12:13:40 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CandidateBasicInfoRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CandidateName,
        CandidateEmail,
        CandidateResume,
        CandidateGender;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CANDIDATENAME = AttributesEnum.CandidateName.index();
    public static final int CANDIDATEEMAIL = AttributesEnum.CandidateEmail.index();
    public static final int CANDIDATERESUME = AttributesEnum.CandidateResume.index();
    public static final int CANDIDATEGENDER = AttributesEnum.CandidateGender.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CandidateBasicInfoRowImpl() {
    }
}

