package model.ViewObject;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 02 14:24:17 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CandidateInterviewHistoryRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InterviewerEmailId,
        InterviewerName,
        EventName,
        RoundNo,
        Status,
        FeedbackId,
        StartTime,
        EndTime;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INTERVIEWEREMAILID = AttributesEnum.InterviewerEmailId.index();
    public static final int INTERVIEWERNAME = AttributesEnum.InterviewerName.index();
    public static final int EVENTNAME = AttributesEnum.EventName.index();
    public static final int ROUNDNO = AttributesEnum.RoundNo.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int FEEDBACKID = AttributesEnum.FeedbackId.index();
    public static final int STARTTIME = AttributesEnum.StartTime.index();
    public static final int ENDTIME = AttributesEnum.EndTime.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CandidateInterviewHistoryRowImpl() {
    }
}

