package model.ViewObject;

import java.math.BigDecimal;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 17:33:30 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompletedEventsVORowImpl extends ViewRowImpl {
    public static final int ENTITY_EVENTDETAILSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        EventId,
        EventStartTime,
        EventEndTime,
        EventStatus,
        EventName,
        CompletedEventsVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int EVENTSTARTTIME = AttributesEnum.EventStartTime.index();
    public static final int EVENTENDTIME = AttributesEnum.EventEndTime.index();
    public static final int EVENTSTATUS = AttributesEnum.EventStatus.index();
    public static final int EVENTNAME = AttributesEnum.EventName.index();
    public static final int COMPLETEDEVENTSVO1 = AttributesEnum.CompletedEventsVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CompletedEventsVORowImpl() {
    }
}

