package model.ViewObject;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 30 15:19:07 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EventCandidatefordetailpageRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CandidateName,
        CandidateEmailId,
        CurrentRound,
        Status,
        EventId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CANDIDATENAME = AttributesEnum.CandidateName.index();
    public static final int CANDIDATEEMAILID = AttributesEnum.CandidateEmailId.index();
    public static final int CURRENTROUND = AttributesEnum.CurrentRound.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int EVENTID = AttributesEnum.EventId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EventCandidatefordetailpageRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CandidateName.
     * @return the CandidateName
     */
    public String getCandidateName() {
        return (String) getAttributeInternal(CANDIDATENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute CandidateEmailId.
     * @return the CandidateEmailId
     */
    public String getCandidateEmailId() {
        return (String) getAttributeInternal(CANDIDATEEMAILID);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentRound.
     * @return the CurrentRound
     */
    public BigDecimal getCurrentRound() {
        return (BigDecimal) getAttributeInternal(CURRENTROUND);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Gets the attribute value for the calculated attribute EventId.
     * @return the EventId
     */
    public BigDecimal getEventId() {
        return (BigDecimal) getAttributeInternal(EVENTID);
    }
}

