package model.ViewObject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 28 19:48:47 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GetEventIdImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GetEventIdImpl() {
    }
}

