package model.ViewObject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 08 22:28:46 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InterviewerCurrentStatusImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InterviewerCurrentStatusImpl() {
    }
}

