package model.ViewObject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 18:09:13 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ScheduledInterviewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InterviewerEmailId,
        CandidateEmailId,
        RoundNo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INTERVIEWEREMAILID = AttributesEnum.InterviewerEmailId.index();
    public static final int CANDIDATEEMAILID = AttributesEnum.CandidateEmailId.index();
    public static final int ROUNDNO = AttributesEnum.RoundNo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ScheduledInterviewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute InterviewerEmailId.
     * @return the InterviewerEmailId
     */
    public String getInterviewerEmailId() {
        return (String) getAttributeInternal(INTERVIEWEREMAILID);
    }

    /**
     * Gets the attribute value for the calculated attribute CandidateEmailId.
     * @return the CandidateEmailId
     */
    public String getCandidateEmailId() {
        return (String) getAttributeInternal(CANDIDATEEMAILID);
    }

    /**
     * Gets the attribute value for the calculated attribute RoundNo.
     * @return the RoundNo
     */
    public Integer getRoundNo() {
        return (Integer) getAttributeInternal(ROUNDNO);
    }
}

