package model.ViewObject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 09 00:11:43 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UpcomingInterviewsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UpcomingInterviewsImpl() {
    }
}

