package model.EntityObject;

import javax.servlet.http.HttpSession;

import model.EntityObject.common.AppModule;

import model.ViewObject.CandidateBasicInfoImpl;
import model.ViewObject.CandidatesAssignedInterviewerImpl;
import model.ViewObject.GetEventIdImpl;
import model.ViewObject.ScheduledInterviewImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;



// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 18:19:36 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for AkmrCandidateDataView1.
     * @return AkmrCandidateDataView1
     */
    public ViewObjectImpl getAkmrCandidateDataView1() {
        return (ViewObjectImpl) findViewObject("AkmrCandidateDataView1");
    }

    /**
     * Container's getter for AkmrEventCandidateDetailsView1.
     * @return AkmrEventCandidateDetailsView1
     */
    public ViewObjectImpl getAkmrEventCandidateDetailsView1() {
        return (ViewObjectImpl) findViewObject("AkmrEventCandidateDetailsView1");
    }

    /**
     * Container's getter for AkmrEventDetailsView1.
     * @return AkmrEventDetailsView1
     */
    public ViewObjectImpl getAkmrEventDetailsView1() {
        return (ViewObjectImpl) findViewObject("AkmrEventDetailsView1");
    }

    /**
     * Container's getter for AkmrEventInterviewerDetailsView1.
     * @return AkmrEventInterviewerDetailsView1
     */
    public ViewObjectImpl getAkmrEventInterviewerDetailsView1() {
        return (ViewObjectImpl) findViewObject("AkmrEventInterviewerDetailsView1");
    }

    /**
     * Container's getter for AkmrFeedbackDetailsView1.
     * @return AkmrFeedbackDetailsView1
     */
    public ViewObjectImpl getAkmrFeedbackDetailsView1() {
        return (ViewObjectImpl) findViewObject("AkmrFeedbackDetailsView1");
    }

    /**
     * Container's getter for AkmrInterviewDetailsView1.
     * @return AkmrInterviewDetailsView1
     */
    public ViewObjectImpl getAkmrInterviewDetailsView1() {
        return (ViewObjectImpl) findViewObject("AkmrInterviewDetailsView1");
    }

    /**
     * Container's getter for AkmrInterviewerDataView1.
     * @return AkmrInterviewerDataView1
     */
    public ViewObjectImpl getAkmrInterviewerDataView1() {
        return (ViewObjectImpl) findViewObject("AkmrInterviewerDataView1");
    }

    /**
     * Container's getter for AkmrUsersMasterView1.
     * @return AkmrUsersMasterView1
     */
    public ViewObjectImpl getAkmrUsersMasterView1() {
        return (ViewObjectImpl) findViewObject("AkmrUsersMasterView1");
    }

    /**
     * Container's getter for CandidatesAssignedInterviewer1.
     * @return CandidatesAssignedInterviewer1
     */
    public CandidatesAssignedInterviewerImpl getCandidatesAssignedInterviewer1() {
        return (CandidatesAssignedInterviewerImpl) findViewObject("CandidatesAssignedInterviewer1");
    }

    /**
     * Container's getter for GetEventId1.
     * @return GetEventId1
     */
    public GetEventIdImpl getGetEventId1() {
        return (GetEventIdImpl) findViewObject("GetEventId1");
    }

    /**
     * Container's getter for CandidateBasicInfo1.
     * @return CandidateBasicInfo1
     */
    public CandidateBasicInfoImpl getCandidateBasicInfo1() {
        return (CandidateBasicInfoImpl) findViewObject("CandidateBasicInfo1");
    }

    /**
     * Container's getter for ScheduledInterview1.
     * @return ScheduledInterview1
     */
    public ScheduledInterviewImpl getScheduledInterview1() {
        return (ScheduledInterviewImpl) findViewObject("ScheduledInterview1");
    }
    
    public String getUserId(String userName) {
        
        System.out.println("IN getuserid ...... " + userName.toString());
            
            
        //userName = "kavan.patel@oracle.com";
        ViewObjectImpl usersVO = this.getScheduledInterview1();
        usersVO.setApplyViewCriteriaName("findByUserName");
        usersVO.setNamedWhereClauseParam("loggedInUserName",userName);
        usersVO.executeQuery();
        Row usersVORow = usersVO.first();
        return (usersVORow != null) ? usersVORow.getAttribute("INTERVIEWER_EMAIL_ID").toString() : null;
        }
}

