package model.EntityObject.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 18:37:41 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String getUserId(String userName);
}

