package model.EntityObject.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 30 16:24:00 IST 2020
// ---------------------------------------------------------------------
public interface RecruitingAppManagement extends ApplicationModule {
    void setBindvar();

    void report_setCandidate();

    void report_setInterviewer();
}

