package model.ViewObjectQB;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 11:34:59 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class approinterviewerImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public approinterviewerImpl() {
    }
}

