package model.ViewObjectQB;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 29 11:31:37 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EventCandidateDatawithNameRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CandidateName,
        CandidateEmailId,
        CurrentRound,
        Status,
        EventId,
        InterviewerList,
        approinterviewer1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CANDIDATENAME = AttributesEnum.CandidateName.index();
    public static final int CANDIDATEEMAILID = AttributesEnum.CandidateEmailId.index();
    public static final int CURRENTROUND = AttributesEnum.CurrentRound.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int INTERVIEWERLIST = AttributesEnum.InterviewerList.index();
    public static final int APPROINTERVIEWER1 = AttributesEnum.approinterviewer1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EventCandidateDatawithNameRowImpl() {
    }
}

