package model.ViewObjectQB;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 08 10:27:05 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class givenInterviewerImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public givenInterviewerImpl() {
    }
}

