package model.ViewObjectQB;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 28 08:59:50 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class interviewdetailQBRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CandidateName,
        InterviewerName,
        RoundNo,
        StartTime,
        Status,
        EventId;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return interviewdetailQBRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return interviewdetailQBRowImpl.AttributesEnum.firstIndex() + interviewdetailQBRowImpl.AttributesEnum
                                                                                                  .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = interviewdetailQBRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CANDIDATENAME = AttributesEnum.CandidateName.index();
    public static final int INTERVIEWERNAME = AttributesEnum.InterviewerName.index();
    public static final int ROUNDNO = AttributesEnum.RoundNo.index();
    public static final int STARTTIME = AttributesEnum.StartTime.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int EVENTID = AttributesEnum.EventId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public interviewdetailQBRowImpl() {
    }
}

