package model.ViewObjectQB;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 08 20:30:23 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class scheduledInterviewsRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CandidateName,
        CandidateEmail,
        InterviewerName,
        InterviewerEmail,
        InterviewerEmailId,
        CandidateEmailId,
        EventId,
        StartTime,
        EndTime,
        RoundNo,
        Status;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CANDIDATENAME = AttributesEnum.CandidateName.index();
    public static final int CANDIDATEEMAIL = AttributesEnum.CandidateEmail.index();
    public static final int INTERVIEWERNAME = AttributesEnum.InterviewerName.index();
    public static final int INTERVIEWEREMAIL = AttributesEnum.InterviewerEmail.index();
    public static final int INTERVIEWEREMAILID = AttributesEnum.InterviewerEmailId.index();
    public static final int CANDIDATEEMAILID = AttributesEnum.CandidateEmailId.index();
    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int STARTTIME = AttributesEnum.StartTime.index();
    public static final int ENDTIME = AttributesEnum.EndTime.index();
    public static final int ROUNDNO = AttributesEnum.RoundNo.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public scheduledInterviewsRowImpl() {
    }
}

