package model.ViewObjectQB;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 30 13:11:17 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SelectedCandidatesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SelectedCandidatesVOImpl() {
    }
}

